server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  datasource:
    name: zh-admin
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat #监控统计拦截的filters
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test-security?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true #基本属性
      username: root
      password: root
      initial-size: 1 #配置初始化大小/最小/最大
      min-idle: 1
      max-active: 20
      max-wait: 60000 #获取连接等待超时时间
      time-between-eviction-runs-millis: 60000 #间隔多久进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 300000 #一个连接在池中最小生存的时间
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    shiro:
      host: 127.0.0.1
      port: 6379
      timeout: 300
      password:

##################mybatis####################
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.zhenghao.zh.**.entity


##################pagehelper分页插件####################
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql


##################Redis config####################
redis:
  database: 0 # Redis数据库索引（默认为0）
  host: 127.0.0.1 # Redis服务器地址
  port: 6379 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
  timeout: 3600 # 连接超时时间（毫秒）
  jedis:
    pool:
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    shutdown-timeout: 100 # jedis超时