zh-admin:
  auth:
    api:
      matches: # 匹配路由,不能重复且不能存在交集, 例：/uploads/-/system/user/avatar 不能与 /uploads 共存
        - /api
        - /uploads/-/system/user/avatar
        - /druid
  file:
    uploads:
      folder: /data/app/zh-admin/uploads/ # 文件上传目录,末尾必有/ 或 \\
      # folder: D:/data/app/zh-admin/uploads/ # 文件上传目录,末尾必有/ 或 \\
      path: /uploads/ # 文件上传静态资源对外暴露的访问路径,末尾必有/
  log:
    # directory: /data/app/zh-admin/log
    directory: log

logging:
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8
    serialization:
      indent_output: true #格式化输出
      fail_on_empty_beans: false #忽略无法转换的对象
    defaultPropertyInclusion: NON_EMPTY #设置空如何序列化
    deserialization:
      fail_on_unknown_properties: false #允许对象忽略json中不存在的属性
    parser:
      allow_unquoted_control_chars: true #允许出现特殊字符和转义符
      allow_single_quotes: true #允许出现单引号

##################mybatis####################
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:mapper/*.xml

##################pagehelper分页插件####################
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql

##################springboot 监控####################
management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace
