server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

zh-admin:
  auth:
    routes: # 有效路由,不能重复且存在交集, 例：/uploads/-/system/user/avatar 不能与 /uploads 共存
      - /api/v1
      - /uploads/-/system/user/avatar
  jwt:
    token-header: ZH-TOKEN
    expire: 14400
    private-key-path: jwt/pkcs8_rsa_private_key.pem
    public-key-path: jwt/rsa_public_key.pem
  file:
    uploads:
      folder: D:\\zh-admin\\uploads # 文件上传目录
      path: /uploads # 文件上传静态资源对外暴露的访问路径

logging:
  config: classpath:logback.xml
  level:
    net.zhenghao.zh.**.dao: debug #dao所在的包文件
    org.springframework.jdbc.core: error
    root: info
    org.hibernate: ERROR

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8
    serialization:
      indent_output: true #格式化输出
      fail_on_empty_beans: false #忽略无法转换的对象
    defaultPropertyInclusion: NON_EMPTY #设置空如何序列化
    deserialization:
      fail_on_unknown_properties: false #允许对象忽略json中不存在的属性
    parser:
      allow_unquoted_control_chars: true #允许出现特殊字符和转义符
      allow_single_quotes: true #允许出现单引号

##################mybatis####################
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: net.zhenghao.zh


##################pagehelper分页插件####################
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql