server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

logging:
  config: classpath:logback.xml
  level:
    net.zhenghao.zh.**.dao: debug #dao所在的包文件
    org.springframework.jdbc.core: error
    root: info
    org.hibernate: ERROR

spring:
  profiles:
    active: dev
  redis:
    shiro:
      host: 127.0.0.1:6379
      timeout: 30
      password: foobared
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: foobared # Redis服务器连接密码（默认为空）
    timeout: 3600 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100 # jedis超时
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    serialization:
      indent_output: true #格式化输出
      fail_on_empty_beans: false #忽略无法转换的对象
    defaultPropertyInclusion: NON_EMPTY #设置空如何序列化
    deserialization:
      fail_on_unknown_properties: false #允许对象忽略json中不存在的属性
    parser:
      allow_unquoted_control_chars: true #允许出现特殊字符和转义符
      allow_single_quotes: true #允许出现单引号

##################mybatis####################
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.zhenghao.zh


##################pagehelper分页插件####################
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql


